function [daily_dis1,daily_dis2] = plot_Pandora_and_TropOMI()
%daily_dis1_file = 'C:\Projects\TropOMI\data\NO2\TropOMI_at_Downsview_daily_dis1.csv';
%daily_dis1_file = 'C:\Projects\TropOMI\data\NO2\TropOMI_at_Downsview_daily_dis1 - Copy.csv'
daily_dis1_file = 'C:\Projects\TropOMI\data\NO2\TropOMI_at_Downsview_summary_dis24.0km.csv';
%daily_dis2_file = 'C:\Projects\TropOMI\data\NO2\TropOMI_at_Downsview_daily_dis2.csv';
daily_dis2_file = 'C:\Projects\TropOMI\data\TropOMI_at_Downsview_summary_dis7.0km.csv';
%daily_dis1_file = 'C:\Projects\TropOMI\data\NO2\TropOMI_at_Egbert_daily_dis1.csv';
%daily_dis2_file = 'C:\Projects\TropOMI\data\NO2\TropOMI_at_Egbert_daily_dis2.csv';
%daily_dis1_file = 'C:\Projects\TropOMI\data\NO2\TropOMI_at_FortMcKay_daily_dis1.csv';
%daily_dis2_file = 'C:\Projects\TropOMI\data\NO2\TropOMI_at_FortMcKay_daily_dis2.csv';

%daily_dis1 = importfile(daily_dis1_file);
%daily_dis2 = importfile(daily_dis2_file);
%daily_dis1 = importfile_v2(daily_dis1_file);
%daily_dis2 = importfile_v2(daily_dis2_file);
load('C:\Projects\TropOMI\data\TropOMI_test.mat');

%Pandora_file = '\\wdow05dtmibroh.ncr.int.ec.gc.ca\GDrive\Pandora\103\Blick\L2\Pandora103s1_Downsview_L2Tot_rnvs0p1.csv';
%load('C:\Projects\TropOMI\temp.mat');
load('C:\Projects\TropOMI\data\P103.mat');
TF = Pandora103.Column12L2dataqualityflagfornitrogendioxide0assuredhighquality1 <=1;
Pandora103(~TF,:) = [];
% TF = Pandora104.Column12L2dataqualityflagfornitrogendioxide0assuredhighquality1 <=1;
% Pandora104(~TF,:) = [];
%TF = Pandora108.Column11L2dataqualityflagfornitrogendioxide0highquality1mediumq <=1;
%Pandora108(~TF,:) = [];
%TF = Pandora122.Column11L2dataqualityflagfornitrogendioxide0highquality1mediumq <=1;
%Pandora122(~TF,:) = [];


Pandora = Pandora103;

% add local time offset
LTC_offset = 13.5/24;
%daily_dis1.LTC = datetime(datestr(datenum(daily_dis1.time) + LTC_offset));
%daily_dis2.LTC = datetime(datestr(datenum(daily_dis2.time) + LTC_offset));
daily_dis1.LTC = datetime(datestr(datenum(daily_dis1.Datetime_coarse) + LTC_offset));
daily_dis2.LTC = datetime(datestr(datenum(daily_dis2.Datetime_coarse) + LTC_offset));

Pandora.LTC = datetime(datestr(datenum(Pandora.time) - 5/24));
%Pandora.LTC = datetime(datestr(datenum(Pandora.time) - 7/24));

% plotting
DU = 2.6870e+16;
figure;hold all;
plot(Pandora.LTC,Pandora.Column8NitrogendioxidetotalverticalcolumnamountDobsonUnits9e99r.*DU,'.');
%plot(Pandora.LTC,Pandora.Column8NitrogendioxidetotalverticalcolumnamountDobsonUnits9e99r,'.');
plot(daily_dis1.LTC,daily_dis1.no2,'.');
plot(daily_dis2.LTC,daily_dis2.no2,'.');
%legend('Pandora','TropOMI 24km','TropOMI 7km');
legend('Pandora','TropOMI 7km','TropOMI 24km');
ylabel('NO_2 total column [molec/cm^2]');



%%
function TropOMIatDownsviewdailydis1 = importfile(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   TROPOMIATDOWNSVIEWDAILYDIS1 = IMPORTFILE(FILENAME) Reads data from text
%   file FILENAME for the default selection.
%
%   TROPOMIATDOWNSVIEWDAILYDIS1 = IMPORTFILE(FILENAME, STARTROW, ENDROW)
%   Reads data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   TropOMIatDownsviewdailydis1 = importfile('TropOMI_at_Downsview_daily_dis1.csv', 2, 16);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2018/05/02 09:56:21

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format for each line of text:
%   column1: datetimes (%{yyyyMMdd}D)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%{yyyyMMdd}D%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
TropOMIatDownsviewdailydis1 = table(dataArray{1:end-1}, 'VariableNames', {'time','no2_trop','no2_trop_err','d','no2'});

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% TropOMIatDownsviewdailydis1.time=datenum(TropOMIatDownsviewdailydis1.time);




